### ISSUE TITLE
Upload speed hidden in tray tooltip

### ISSUE THREAD

**Issue by XinHong** [transmission-remote-gui/transgui#1036]
Hello,

Since 5.12 the upload speed is not available anymore

In 5.11:
![3 11](https://user-images.githubusercontent.com/2780601/33523482-eabeea9c-d808-11e7-94c5-c1fc39e74c61.png)

In 5.12:
![3 12](https://user-images.githubusercontent.com/2780601/33523491-0974869a-d809-11e7-8df7-f84ef7bbc7b5.png)

**Comment by antekgla** [comment]
Fix this with https://github.com/transmission-remote-gui/transgui/commit/6a96f67d443940af8b4bb1b1524b4046fc816479

![transgui tray](https://user-images.githubusercontent.com/24402722/33526979-8f9194ac-d827-11e7-9ae4-8e67f0dbd88b.jpg)

Sorry about that, the bug was introduced at including Global Speed Limits in StatusBar :confused:

**Comment by XinHong** [comment]
Thanks :)
