### ISSUE TITLE
The customized shortcut key (introduced in #924) result in blank panes in 5.13 on Windows 10 1709

### ISSUE THREAD

**Issue by kissglay** [transmission-remote-gui/transgui#1063]
In 5.13, customized shortcut keys like "Alt + P"(Info Pane - Peers Tab), "Alt + G"(Info Pane - General Tab) and so on introduced in [https://github.com/transmission-remote-gui/transgui/issues/924](url) result in blank pane when these pane are focused by these shortcut keys, but focusing  them by mouse clicking or "Tab -> arrow key" works fine.

**Comment by antekgla** [comment]
And in 5.12 that shortcuts works fine?

**Comment by kissglay** [comment]
Yes. In 5.12 it's fine.
Now in 5.13.0, when hit "Alt + P", it's what it looks like:
![greenshot-2018-01-07 21_52_03-transmission remote gui v5 13](https://user-images.githubusercontent.com/529385/34650062-58cf8a8e-f3f5-11e7-95cc-ae345c9b38d9.png)

**Comment by antekgla** [comment]
What is your system?
Windows, Linux, Mac?

**Comment by kissglay** [comment]
Windows 10 1709

**Comment by antekgla** [comment]
It works fine in my W7....
Let me find a W10 machine and I do some more testing....

**Comment by antekgla** [comment]
Well after some testing I can see this:

1.- With the current source code compiled in Lazarus 1.6 works Ok in W7 & W10.
2.- With the current source code compiled in Lazarus 1.8 the shortcuts works but the behavior is as @kissglay say in W7 & W10.

So to conclude the problem is Lazarus 1.8 maybe @leonsoft-kras & @PeterDaveHello have to view if  using Lazarus 1.8 is a good choice.

**Comment by antekgla** [comment]
I'm trying to fix this but at commit (with Desktop Github in Windows) this error came up.

![git error](https://user-images.githubusercontent.com/24402722/34835619-147a91e4-f6d4-11e7-88ca-3323a3e05837.jpg)

@leonsoft-kras or @PeterDaveHello can solve this?

**Comment by PeterDaveHello** [comment]
@antekgla Try to use another branch or use pull request?

**Comment by antekgla** [comment]
> @antekgla Try to use another branch or use pull request?

@PeterDaveHello or you ( or @leonsoft-kras ) can give me access to push to the master branch.

**Comment by PeterDaveHello** [comment]
@antekgla I set you the owner of the whole project now, but personally, I still strongly recommend you to push to another branch first, let the CI test all the build process, and even let the issuer/reporter to use the build artifacts from CI to test if the results are as expect, this can help the whole project reliability and quality 😄

**Comment by antekgla** [comment]
@PeterDaveHello Ok, thanks for the access.
I push this last commit directly to the master branch because I have already done it in my Github Desktop and frankly I dont know how to undo it. Only have pending the push.
In the future I will try to make the push to another branch ( I have to create it first?)

Regarding to the subject of this Issue I want to thank to the nice people of [Lazarus forum](https://forum.lazarus.freepascal.org/index.php/topic,39210.75.html) specially to **Getmem** what nicely give me the answer to this issue, remarking what the problem is what in [Lazarus 1.8](http://wiki.freepascal.org/Lazarus_1.8.0_release_notes#Changes_affecting_compatibility) the Onchange event of the TTabControl in not automatically called when you change the Tab Page programatically.
