### ISSUE TITLE
the content of the drop-down list is displayed in English instead of the local language

### ISSUE THREAD

**Issue by uniss2209** [transmission-remote-gui/transgui#1082]
![2018-02-15 18_50_35-transmission remote gui v5 14](https://user-images.githubusercontent.com/24721923/36269306-88965ab8-1281-11e8-83e4-a83508f515e7.png)
![2018-02-15 18_54_40-c__program files x86 _transmission remote gui_lang_transgui uk - editplus](https://user-images.githubusercontent.com/24721923/36269414-c729a05a-1281-11e8-80f1-f5f60eb1766e.png)

**Comment by antekgla** [comment]
Fixed with https://github.com/transmission-remote-gui/transgui/commit/fbc418b06d1a28122ca0bd805e5e5fb5e39a7512

![bidi](https://user-images.githubusercontent.com/24402722/36287587-9308cf36-1294-11e8-92f8-a03f0f569f14.jpg)


Also I added code in  https://github.com/transmission-remote-gui/transgui/commit/e23e9ad0ec937657c4ec2e68acf4be09bc813926 to OnActivate form to fix the width of dropdown list when the items are wider that english. Thanks to **wp** from [Lazarus Forum](https://forum.lazarus.freepascal.org/index.php?topic=39420.0) for this fix

**Comment by PeterDaveHello** [comment]
[v5.15.0](https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.0) released.
