### ISSUE TITLE
Feature request: Add custum column about "tag" etc.

### ISSUE THREAD

**Issue by ledudu** [transmission-remote-gui/transgui#1125]
Is there any possible to add custum column?
Like utorrent's "labels"
Sorry for my poor english.

**Comment by antekgla** [comment]
It is not...
TransGUI only can deal with the fields defined in Transmission Daemon.
That is a question for the Transmission Developers.
The subject of labels has been requested for years but Transmission Developers dont implement it.... I don´t know the reason.
Here [#2175](https://trac.transmissionbt.com/ticket/2175) and [#5385](https://trac.transmissionbt.com/ticket/5385) are request for this feature in Transmission Trac Support. The first is **9 years old** and still not implement.

I dont say what is impossible do it locally but not would be practical because all the labels are lost if you use another TransGUI install in another machine.

**Comment by ledudu** [comment]
Thank you for your info.
I always use transGUI. In my mind ,this perhaps like  addition db to query.
^_^ Just hope.
