### ISSUE TITLE
Absolute path error when adding torrents

### ISSUE THREAD

**Issue by itlists** [transmission-remote-gui/transgui#1270]
Hello, 
Running the most recent release 5.18 and having an issue which didn't exist in previous versions.

When adding new torrents (either magnet or .torrent files), there's an error that pops up:
"download directory path is not absolute"

Unable to add a torrent with this app.

If using web browser to connect to transmission rpc gui, there's no error when adding torrents.

Thanks!

**Comment by chpasha** [comment]
Have same error. I workaround it by selecting some short path first for instance xxx/Download and then choosing "set data location" from context menu

**Comment by Kethsar** [comment]
I've encountered this quite a bit in all versions, and I am fairly certain it has to do with the MaxFoldersHistory setting. Once you cap your directory history it starts giving this error if you are setting the download directory to a new one. I usually work around it by manually removing some of the saved directories from the INI file ~~but it is rather annoying that it doesn't just prune the oldest entry~~.

As I was writing this I decided to confirm whether or not it automatically trims the directory history, and it certainly tries. However it fails and I am guessing this causes the text in the Destination Folder text box to be removed, or something. I can't tell, really. Lazarus is dumb and seems to have a hard time accessing objects currently in scope in code, or even accessing parts of an object you can manage to inspect. So it's kinda hard to tell whether the text gets deleted or what.

After more debugging I found the text does indeed seem to get cleared from the Destination Folder text box. This means an empty string is sent as the destination directory to Transmission, causing the "download directory path is not absolute" message. I did manage to fix this locally by adding `cbDestFolder.Text:=s;` at the end of the `try` block in the `OKButtonClick` function of addtorrent.pas. This seems like a rather questionable fix so I will leave it to the developers to figure out something proper.

Final findings: if directories are being pruned from the saved directory history, this error will happen. This includes using a directory already in the list, if the MaxFoldersHistory has been changed since the last torrent was added, and triggers a pruning. Setting the text of cbDestFolder after a pruning fixes the issue.

**Comment by leonsoft-kras** [comment]
helpful information. thanks.
