### ISSUE TITLE
Status bar items doesn't fit

### ISSUE THREAD

**Issue by spvkgn** [transmission-remote-gui/transgui#953]
There are odd spaces between:

![transgui-statusbar](https://user-images.githubusercontent.com/4147135/27068882-0c842302-5034-11e7-9ae4-d6b93644bffa.png)

**Comment by PeterDaveHello** [comment]
@spvkgn what's the version and platform you are using please?

**Comment by spvkgn** [comment]
@PeterDaveHello I'm using 5.7.0 on Ubuntu 17.04

**Comment by PeterDaveHello** [comment]
@spvkgn what's your desktop environment please?

**Comment by spvkgn** [comment]
@PeterDaveHello MATE 1.18

**Comment by leonsoft-kras** [comment]
I watched recently, for the statusbar, the author assigned a fixed size. Automatic selection of the width of the elements is not provided. So everything is not so simple.

**Comment by antekgla** [comment]
I update this fix https://github.com/transmission-remote-gui/transgui/commit/2e7c2d5ec015efbb318b9cb258f915bde0eb9bdb
Now the statusbar panels widths are tied to the screen resolution. 
If you change your screen resolution the panels widths are reset to the default.
So if you customize your statusbar panels widths and for some reason you have to change your screen resolution and later come back, please copy the **[statusbarpanels]** section of your _transgui.ini_ because would be erased and re-created.
