### ISSUE TITLE
Feature: Clear search string

### ISSUE THREAD

**Issue by AllanMarcus** [transmission-remote-gui/transgui#985]
Any change of added a little "x" to the right of the search field to clear the search string? This little "X" to clear a field has become ubiquitous, and I think it would be very useful here.

Alternatively, since the little magnifying glass icon to the left of the field is just a graphic, may click on that to clear the field. The "x" to the right of the field, however, would be better a UI choice.

**Comment by antekgla** [comment]
I dont know for what you need this because pressing Esc when in Search box all the text is erased, but it is so easy to implement what I did it in https://github.com/transmission-remote-gui/transgui/commit/f7367b1248daa187dadd24acf5905422b0020163

![cancelsearchbutton](https://user-images.githubusercontent.com/24402722/33499084-496ae6f2-d6b2-11e7-8712-dde14cb16554.jpg)

**Comment by odinian** [comment]
Great! I didn't know ESC did that. Thanks for the ESC and the botton option.
